  <tr id="msg<?=$message['id']?>">
    <td><?=$message['id']?></td>
    <td><?=$message['name']?></td>
    <td><?=$message['phone']?></td>
    <td><?=$message['email']?></td>
    <td><?=$message['text']?></td>
    <td><?=date("Y-M-d", strtotime($message['add_date']))?></td>
    <td width="7%"><?php echo $this->tag->linkTo(array('messages/edit/'.$message['id'], '<i class="glyphicon glyphicon-edit"></i> Edit', 'class' => 'btn btn-default')); ?></td>
    <td width="7%"><?php echo $this->tag->linkTo(array('#', '<i class="glyphicon glyphicon-remove"></i> Delete', 'onclick'=>'if (confirm(\'Delete?\')) { messageDelete('.$message['id'].'); return false; }', 'class' => 'btn btn-default')); ?></td>
  </tr>

