<?php 
include('header.phtml');

echo '<h1>Messages list</h1>';

$this->getContent();
//vdump_e($this->session->get('name'));

?>

<table class="table table-bordered table-striped" align="center">
    <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Message</th>
          <th>Date</th>
          <th colspan="2">&nbsp;</th>
        </tr>
    </thead>
    <tbody>
      <form id="message_search_form" action="/index/index/" method="post">
        <tr><input type="hidden" name="search" value="1">
            <td>&nbsp;</td>
            <td><input type="text" id="search_name" name="name" value="<?=$this->session->get('name')?>" class="form-control"></td>
            <td><input type="text" id="search_phone" name="phone" value="<?=$this->session->get('phone')?>" class="form-control"></td>
            <td><input type="text" id="search_email" name="email" value="<?=$this->session->get('email')?>" class="form-control"></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td colspan="2" align="center"><input type="submit" value="Search" class="btn"></td>
        </tr>
      </form>
    </tbody>
    <tbody>
      <form id="message_add_form">
        <tr>
            <td>&nbsp;</td>
            <td><input type="text" id="name" name="name" class="form-control"></td>
            <td><input type="text" id="phone" name="phone" class="form-control"></td>
            <td><input type="text" id="email" name="email" class="form-control"></td>
            <td><input type="text" id="text" name="text" class="form-control"></td>
            <td>&nbsp;</td>
            <td colspan="2" align="center"><input type="submit" value="Create Message" class="btn btn-success"></td>
        </tr>
      </form>
    </tbody>


<tbody>

<?php

if (isset($page) && count($page->items)) { 

    foreach ($page->items as $i=>$message) { 

        if ($i==0) { 

?>
<?php
        }
?>
  <tr id="msg<?=$message->id?>">
    <td><?=$message->id?></td>
    <td><?=$message->name?></td>
    <td><?=$message->phone?></td>
    <td><?=$message->email?></td>
    <td><?=$message->text?></td>
    <td><?=date("Y-M-d", strtotime($message->add_date))?></td>
    <td width="7%"><?php echo $this->tag->linkTo(array('index/edit/'.$message->id, '<i class="glyphicon glyphicon-edit"></i> Edit', 'class' => 'btn btn-default')); ?></td>
    <td width="7%"><?php echo $this->tag->linkTo(array('#', '<i class="glyphicon glyphicon-remove"></i> Delete', 'onclick'=>'if (confirm(\'Delete?\')) { messageDelete('.$message->id.'); return false; }', 'class' => 'btn btn-default')); ?></td>
  </tr>
<?php

        if ($i==(count($page->items)-1)) { 

?>
</tbody>

<?php
            if (1 < $page->total_pages) {
?>
    <tbody>
        <tr>
            <td colspan="8" align="right">
                <div class="btn-group">
                    <?php echo $this->tag->linkTo(array('index/index', '<i class="icon-fast-backward"></i> First', 'class' => 'btn btn-default')); ?>
                    <?php echo $this->tag->linkTo(array('index/index?page=' . $page->before, '<i class="icon-step-backward"></i> Previous', 'class' => 'btn btn-default')); ?>
                    <?php echo $this->tag->linkTo(array('index/index?page=' . $page->next, '<i class="icon-step-forward"></i> Next', 'class' => 'btn btn-default')); ?>
                    <?php echo $this->tag->linkTo(array('index/index?page=' . $page->last, '<i class="icon-fast-forward"></i> Last', 'class' => 'btn btn-default')); ?>
                    <span class="help-inline"><?php echo $page->current; ?>/<?php echo $page->total_pages; ?></span>
                </div>
            </td>
        </tr>
    </tbody>

<?php
            }
?>

<?php
        }
    }
}
else
{

?>
  No messages in database
<?php
}
?>

  </table>

<script type="text/javascript">
  messageAdd();
</script>

<?

include('footer.phtml');
?>


